FROM docker:dind  as installer
COPY awscliv2.zip .
RUN apk update - \
  && apk add unzip less groff \
  && unzip awscliv2.zip \
  && ./aws/install --bin-dir /aws-cli-bin/
WORKDIR /aws
ENTRYPOINT ["/bin/sh"]
